version: '3.3'
networks:
  proxy_proxy:
    external: true
services:
  mongo:
    ## Mongo database for both kadira-engine and kadira-ui
    image: mongo:3.4
    volumes:
      - "/data/db"
    command: mongod --smallfiles --replSet kadira
    networks:
      - proxy_proxy
    restart: always
    labels:
      - "traefik.enable=false"

  kadira-engine:
    ## This is the endpoint where Meteor app sends performance data
    image: vladgolubev/kadira-engine
    environment:
      - PORT=11011
      - MONGO_URL=mongodb://mongo/kadira?replicaSet=kadira
      - MONGO_SHARD_URL_one=mongodb://mongo/kadira?replicaSet=kadira
    networks:
      - proxy_proxy
    depends_on:
      - mongo
    restart: always
    labels:
      - "traefik.http.routers.kadira_engine.rule=Host(`${ENGINE_HOST}`)"
      - "traefik.http.routers.kadira_engine.entrypoints=websecure"
      - "traefik.http.routers.kadira_engine.tls=true"
      - "traefik.http.routers.kadira_engine.tls.certresolver=leresolver"
      - "traefik.http.services.kadira_engine.loadbalancer.server.port=11011"

  kadira-rma:
    ## This computes statistics databases every minute.
    image: vladgolubev/kadira-rma
    environment:
      - MONGO_URL=mongodb://mongo/kadira
    depends_on:
      - mongo
    networks:
      - proxy_proxy
    restart: always

  kadira-ui:
    ## Meteor app that presents the Kadira user interface.
    image: vladgolubev/kadira-ui
    #ports:
      #- "80:4000"
      #- "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo/kadira
      - MONGO_SHARD_URL_one=mongodb://mongo/kadira
    depends_on:
      - mongo
    restart: always
    networks:
      - proxy_proxy
    labels:
      - "traefik.http.routers.kadira_ui.rule=Host(`${UI_HOST}`)"
      - "traefik.http.routers.kadira_ui.entrypoints=websecure"
      - "traefik.http.routers.kadira_ui.tls=true"
      - "traefik.http.routers.kadira_ui.tls.certresolver=leresolver"
      - "traefik.http.services.kadira_ui.loadbalancer.server.port=4000"
  
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command: traefik --docker --acme=true --acme.domains='${UI_HOST},${ENGINE_HOST}' --acme.email='${EMAIL}' --acme.httpChallenge.entryPoint=http --acme.entrypoint=https --acme.storage=acme.json --defaultentrypoints=http,https --defaultentrypoints=https --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS'
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

